export const MODAL_CARD_REVIEW = 'MODAL_CARD_REVIEW';
export const MODAL_CARD_OWNER = 'MODAL_CARD_OWNER';
export const MODAL_DETAILS = 'MODAL_DETAILS';
export const MODAL_FILTER = 'MODAL_FILTER';
export const MODAL_FILTER_CATEGORIES = 'MODAL_FILTER_CATEGORIES';
