export const FIND_PANEL = 'FIND_PANEL';
export const POST_PANEL = 'POST_PANEL';
export const BOARD_PANEL = 'BOARD_PANEL';
export const PROFILE_PANEL = 'PROFILE_PANEL';
export const RATING_PANEL = 'RATING_PANEL';
export const CENTER_EDIT_PANEL = 'CENTER_EDIT_PANEL';
export const MAPVIEW_PANEL = 'MAPVIEW_PANEL';
export const CITY_SELECTION_PANEL = 'CHOISE_CITY_PANEL';

